"""initial migration

Revision ID: c31b1c110e5e
Revises: 
Create Date: 2024-12-04 14:29:40.352421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c31b1c110e5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SLA_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sub_customer_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sla_start', sa.DateTime(), nullable=False),
    sa.Column('sla_due', sa.DateTime(), nullable=False),
    sa.Column('ticket_status', sa.String(length=255), nullable=False),
    sa.Column('sla_status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('sla_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('SLA_log', schema=None) as batch_op:
        batch_op.create_index('sla_log_created_at', ['created_at'], unique=False)
        batch_op.create_index('sla_log_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('sla_log_id', ['id'], unique=False)
        batch_op.create_index('sla_log_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('sla_log_sla_due', ['sla_due'], unique=False)
        batch_op.create_index('sla_log_sla_start', ['sla_start'], unique=False)
        batch_op.create_index('sla_log_sla_status', ['sla_status'], unique=False)
        batch_op.create_index('sla_log_sla_type', ['sla_type'], unique=False)
        batch_op.create_index('sla_log_sub_customer_id', ['sub_customer_id'], unique=False)
        batch_op.create_index('sla_log_ticket_id', ['ticket_id'], unique=False)
        batch_op.create_index('sla_log_ticket_status', ['ticket_status'], unique=False)

    op.create_table('SLA_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sub_customer_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=255), nullable=True),
    sa.Column('ticket_type', sa.String(length=255), nullable=True),
    sa.Column('response_time_sla', sa.Integer(), nullable=True),
    sa.Column('resolve_time_sla', sa.Integer(), nullable=True),
    sa.Column('business_hr_bypass', sa.String(length=255), nullable=True),
    sa.Column('holiday_hour_bypass', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('SLA_master', schema=None) as batch_op:
        batch_op.create_index('sla_master_business_hr_bypass', ['business_hr_bypass'], unique=False)
        batch_op.create_index('sla_master_created_at', ['created_at'], unique=False)
        batch_op.create_index('sla_master_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('sla_master_holiday_hour_bypass', ['holiday_hour_bypass'], unique=False)
        batch_op.create_index('sla_master_id', ['id'], unique=False)
        batch_op.create_index('sla_master_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('sla_master_priority', ['priority'], unique=False)
        batch_op.create_index('sla_master_resolve_time_sla', ['resolve_time_sla'], unique=False)
        batch_op.create_index('sla_master_response_time_sla', ['response_time_sla'], unique=False)
        batch_op.create_index('sla_master_severity', ['severity'], unique=False)
        batch_op.create_index('sla_master_sub_customer_id', ['sub_customer_id'], unique=False)
        batch_op.create_index('sla_master_ticket_type', ['ticket_type'], unique=False)

    with op.batch_alter_table('business_hour', schema=None) as batch_op:
        batch_op.create_index('business_hour_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('business_hour_day', ['day'], unique=False)
        batch_op.create_index('business_hour_ending_time', ['ending_time'], unique=False)
        batch_op.create_index('business_hour_id', ['id'], unique=False)
        batch_op.create_index('business_hour_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('business_hour_starting_time', ['starting_time'], unique=False)
        batch_op.create_index('business_hour_weekly_holiday', ['weekly_holiday'], unique=False)

    with op.batch_alter_table('customer_master', schema=None) as batch_op:
        batch_op.create_index('customer_master_active_flag', ['active_flag'], unique=False)
        batch_op.create_index('customer_master_created_at', ['created_at'], unique=False)
        batch_op.create_index('customer_master_customer_email', ['customer_email'], unique=False)
        batch_op.create_index('customer_master_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('customer_master_customer_name', ['customer_name'], unique=False)
        batch_op.create_index('customer_master_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('customer_master_updated_at', ['updated_at'], unique=False)

    with op.batch_alter_table('function_master', schema=None) as batch_op:
        batch_op.create_index('function_master_created_at', ['created_at'], unique=False)
        batch_op.create_index('function_master_function_code', ['function_code'], unique=False)
        batch_op.create_index('function_master_function_name', ['function_name'], unique=False)
        batch_op.create_index('function_master_id', ['id'], unique=False)
        batch_op.create_index('function_master_is_encrypted', ['is_encrypted'], unique=False)

    with op.batch_alter_table('holiday_master', schema=None) as batch_op:
        batch_op.create_index('holiday_master_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('holiday_master_day', ['day'], unique=False)
        batch_op.create_index('holiday_master_description', ['description'], unique=False)
        batch_op.create_index('holiday_master_id', ['id'], unique=False)
        batch_op.create_index('holiday_master_is_encrypted', ['is_encrypted'], unique=False)

    with op.batch_alter_table('logged_in_users', schema=None) as batch_op:
        batch_op.create_index('logged_in_user_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('logged_in_user_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('logged_in_user_is_logout', ['is_logout'], unique=False)
        batch_op.create_index('logged_in_user_loggedin_at', ['loggedin_at'], unique=False)
        batch_op.create_index('logged_in_user_logout_at', ['logout_at'], unique=False)
        batch_op.create_index('logged_in_user_srno', ['srno'], unique=False)
        batch_op.create_index('logged_in_user_userid', ['userid'], unique=False)

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.alter_column('otp',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_index('otp_created_at', ['created_at'], unique=False)
        batch_op.create_index('otp_id', ['id'], unique=False)
        batch_op.create_index('otp_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('otp_otp', ['otp'], unique=False)
        batch_op.create_index('otp_userid', ['userid'], unique=False)
        batch_op.create_index('otp_uuid', ['uuid'], unique=False)
        batch_op.create_index('otp_verified_at', ['verified_at'], unique=False)
        batch_op.create_index('otp_verified_flag', ['verified_flag'], unique=False)

    with op.batch_alter_table('role_function_mapping', schema=None) as batch_op:
        batch_op.create_index('role_function_mapping_created_at', ['created_at'], unique=False)
        batch_op.create_index('role_function_mapping_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('role_function_mapping_function_id', ['function_id'], unique=False)
        batch_op.create_index('role_function_mapping_id', ['id'], unique=False)
        batch_op.create_index('role_function_mapping_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('role_function_mapping_role_id', ['role_id'], unique=False)

    with op.batch_alter_table('role_master', schema=None) as batch_op:
        batch_op.create_index('role_master_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('role_master_role_id', ['role_id'], unique=False)
        batch_op.create_index('role_master_role_name', ['role_name'], unique=False)

    with op.batch_alter_table('ticket_event_log', schema=None) as batch_op:
        batch_op.create_index('ticket_event_log_event_datetime', ['event_datetime'], unique=False)
        batch_op.create_index('ticket_event_log_event_description', ['event_description'], unique=False)
        batch_op.create_index('ticket_event_log_id', ['id'], unique=False)
        batch_op.create_index('ticket_event_log_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('ticket_event_log_ticket_id', ['ticket_id'], unique=False)

    with op.batch_alter_table('ticket_false_flag', schema=None) as batch_op:
        batch_op.create_index('ticket_false_flag_date_time', ['date_time'], unique=False)
        batch_op.create_index('ticket_false_flag_is_false', ['is_false'], unique=False)
        batch_op.create_index('ticket_false_flag_srno', ['srno'], unique=False)
        batch_op.create_index('ticket_false_flag_ticketid', ['ticketid'], unique=False)

    with op.batch_alter_table('ticket_master', schema=None) as batch_op:
        batch_op.create_index('ticket_master_bucket', ['bucket'], unique=False)
        batch_op.create_index('ticket_master_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ticket_master_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('ticket_master_priority', ['priority'], unique=False)
        batch_op.create_index('ticket_master_raised_at', ['raised_at'], unique=False)
        batch_op.create_index('ticket_master_raised_by_id', ['raised_by_id'], unique=False)
        batch_op.create_index('ticket_master_resolved_by_id', ['resolved_by_id'], unique=False)
        batch_op.create_index('ticket_master_severity', ['severity'], unique=False)
        batch_op.create_index('ticket_master_status', ['status'], unique=False)
        batch_op.create_index('ticket_master_ticket_id', ['ticket_id'], unique=False)
        batch_op.create_index('ticket_master_title', ['title'], unique=False)
        batch_op.create_index('ticket_master_type', ['type'], unique=False)
        batch_op.create_index('ticket_master_updated_at', ['updated_at'], unique=False)

    with op.batch_alter_table('ticket_resolution', schema=None) as batch_op:
        batch_op.create_index('ticket_resolution_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ticket_resolution_id', ['id'], unique=False)
        batch_op.create_index('ticket_resolution_insert_date', ['insert_date'], unique=False)
        batch_op.create_index('ticket_resolution_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('ticket_resolution_resolution_by', ['resolution_by'], unique=False)
        batch_op.create_index('ticket_resolution_ticket_id', ['ticket_id'], unique=False)
        batch_op.create_index('ticket_resolution_title', ['title'], unique=False)
        batch_op.create_index('ticket_resolution_transaction_id', ['transaction_id'], unique=False)

    with op.batch_alter_table('ticket_transaction', schema=None) as batch_op:
        batch_op.create_index('ticket_transaction_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ticket_transaction_group_assign_flag', ['group_assign_flag'], unique=False)
        batch_op.create_index('ticket_transaction_group_assigned_name', ['group_assigned_name'], unique=False)
        batch_op.create_index('ticket_transaction_id', ['id'], unique=False)
        batch_op.create_index('ticket_transaction_insert_date', ['insert_date'], unique=False)
        batch_op.create_index('ticket_transaction_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('ticket_transaction_level', ['level'], unique=False)
        batch_op.create_index('ticket_transaction_ticket_id', ['ticket_id'], unique=False)
        batch_op.create_index('ticket_transaction_user_assign_flag', ['user_assign_flag'], unique=False)
        batch_op.create_index('ticket_transaction_user_assigned_id', ['user_assigned_id'], unique=False)

    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.create_index('ticket_type_created_at', ['created_at'], unique=False)
        batch_op.create_index('ticket_type_id', ['id'], unique=False)
        batch_op.create_index('ticket_type_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('ticket_type_name', ['name'], unique=False)
        batch_op.create_index('ticket_type_ticket_code', ['ticket_code'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('user_active_flag', ['active_flag'], unique=False)
        batch_op.create_index('user_created_at', ['created_at'], unique=False)
        batch_op.create_index('user_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('user_email', ['email'], unique=False)
        batch_op.create_index('user_first_login', ['first_login'], unique=False)
        batch_op.create_index('user_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('user_password', ['password'], unique=False)
        batch_op.create_index('user_phone', ['phone'], unique=False)
        batch_op.create_index('user_role_id', ['role_id'], unique=False)
        batch_op.create_index('user_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('user_user_id', ['user_id'], unique=False)
        batch_op.create_index('user_username', ['username'], unique=False)

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.create_index('user_groups_created_at', ['created_at'], unique=False)
        batch_op.create_index('user_groups_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('user_groups_id', ['id'], unique=False)
        batch_op.create_index('user_groups_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('user_groups_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('user_groups_user_group', ['user_group'], unique=False)
        batch_op.create_index('user_groups_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_index('workflow_can_close', ['can_close'], unique=False)
        batch_op.create_index('workflow_can_pickup', ['can_pickup'], unique=False)
        batch_op.create_index('workflow_can_transfer', ['can_transfer'], unique=False)
        batch_op.create_index('workflow_created_at', ['created_at'], unique=False)
        batch_op.create_index('workflow_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('workflow_id', ['id'], unique=False)
        batch_op.create_index('workflow_initiator_group', ['initiator_group'], unique=False)
        batch_op.create_index('workflow_is_encrypted', ['is_encrypted'], unique=False)
        batch_op.create_index('workflow_order', ['order'], unique=False)
        batch_op.create_index('workflow_parent_customer_id', ['parent_customer_id'], unique=False)
        batch_op.create_index('workflow_sla_id', ['sla_id'], unique=False)
        batch_op.create_index('workflow_terminator_group', ['terminator_group'], unique=False)
        batch_op.create_index('workflow_user_group_name', ['user_group_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('workflow_user_group_name')
        batch_op.drop_index('workflow_terminator_group')
        batch_op.drop_index('workflow_sla_id')
        batch_op.drop_index('workflow_parent_customer_id')
        batch_op.drop_index('workflow_order')
        batch_op.drop_index('workflow_is_encrypted')
        batch_op.drop_index('workflow_initiator_group')
        batch_op.drop_index('workflow_id')
        batch_op.drop_index('workflow_customer_id')
        batch_op.drop_index('workflow_created_at')
        batch_op.drop_index('workflow_can_transfer')
        batch_op.drop_index('workflow_can_pickup')
        batch_op.drop_index('workflow_can_close')

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_index('user_groups_user_id')
        batch_op.drop_index('user_groups_user_group')
        batch_op.drop_index('user_groups_updated_at')
        batch_op.drop_index('user_groups_is_encrypted')
        batch_op.drop_index('user_groups_id')
        batch_op.drop_index('user_groups_customer_id')
        batch_op.drop_index('user_groups_created_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('user_username')
        batch_op.drop_index('user_user_id')
        batch_op.drop_index('user_updated_at')
        batch_op.drop_index('user_role_id')
        batch_op.drop_index('user_phone')
        batch_op.drop_index('user_password')
        batch_op.drop_index('user_is_encrypted')
        batch_op.drop_index('user_first_login')
        batch_op.drop_index('user_email')
        batch_op.drop_index('user_customer_id')
        batch_op.drop_index('user_created_at')
        batch_op.drop_index('user_active_flag')

    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.drop_index('ticket_type_ticket_code')
        batch_op.drop_index('ticket_type_name')
        batch_op.drop_index('ticket_type_is_encrypted')
        batch_op.drop_index('ticket_type_id')
        batch_op.drop_index('ticket_type_created_at')

    with op.batch_alter_table('ticket_transaction', schema=None) as batch_op:
        batch_op.drop_index('ticket_transaction_user_assigned_id')
        batch_op.drop_index('ticket_transaction_user_assign_flag')
        batch_op.drop_index('ticket_transaction_ticket_id')
        batch_op.drop_index('ticket_transaction_level')
        batch_op.drop_index('ticket_transaction_is_encrypted')
        batch_op.drop_index('ticket_transaction_insert_date')
        batch_op.drop_index('ticket_transaction_id')
        batch_op.drop_index('ticket_transaction_group_assigned_name')
        batch_op.drop_index('ticket_transaction_group_assign_flag')
        batch_op.drop_index('ticket_transaction_customer_id')

    with op.batch_alter_table('ticket_resolution', schema=None) as batch_op:
        batch_op.drop_index('ticket_resolution_transaction_id')
        batch_op.drop_index('ticket_resolution_title')
        batch_op.drop_index('ticket_resolution_ticket_id')
        batch_op.drop_index('ticket_resolution_resolution_by')
        batch_op.drop_index('ticket_resolution_is_encrypted')
        batch_op.drop_index('ticket_resolution_insert_date')
        batch_op.drop_index('ticket_resolution_id')
        batch_op.drop_index('ticket_resolution_customer_id')

    with op.batch_alter_table('ticket_master', schema=None) as batch_op:
        batch_op.drop_index('ticket_master_updated_at')
        batch_op.drop_index('ticket_master_type')
        batch_op.drop_index('ticket_master_title')
        batch_op.drop_index('ticket_master_ticket_id')
        batch_op.drop_index('ticket_master_status')
        batch_op.drop_index('ticket_master_severity')
        batch_op.drop_index('ticket_master_resolved_by_id')
        batch_op.drop_index('ticket_master_raised_by_id')
        batch_op.drop_index('ticket_master_raised_at')
        batch_op.drop_index('ticket_master_priority')
        batch_op.drop_index('ticket_master_is_encrypted')
        batch_op.drop_index('ticket_master_customer_id')
        batch_op.drop_index('ticket_master_bucket')

    with op.batch_alter_table('ticket_false_flag', schema=None) as batch_op:
        batch_op.drop_index('ticket_false_flag_ticketid')
        batch_op.drop_index('ticket_false_flag_srno')
        batch_op.drop_index('ticket_false_flag_is_false')
        batch_op.drop_index('ticket_false_flag_date_time')

    with op.batch_alter_table('ticket_event_log', schema=None) as batch_op:
        batch_op.drop_index('ticket_event_log_ticket_id')
        batch_op.drop_index('ticket_event_log_is_encrypted')
        batch_op.drop_index('ticket_event_log_id')
        batch_op.drop_index('ticket_event_log_event_description')
        batch_op.drop_index('ticket_event_log_event_datetime')

    with op.batch_alter_table('role_master', schema=None) as batch_op:
        batch_op.drop_index('role_master_role_name')
        batch_op.drop_index('role_master_role_id')
        batch_op.drop_index('role_master_is_encrypted')

    with op.batch_alter_table('role_function_mapping', schema=None) as batch_op:
        batch_op.drop_index('role_function_mapping_role_id')
        batch_op.drop_index('role_function_mapping_is_encrypted')
        batch_op.drop_index('role_function_mapping_id')
        batch_op.drop_index('role_function_mapping_function_id')
        batch_op.drop_index('role_function_mapping_customer_id')
        batch_op.drop_index('role_function_mapping_created_at')

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_index('otp_verified_flag')
        batch_op.drop_index('otp_verified_at')
        batch_op.drop_index('otp_uuid')
        batch_op.drop_index('otp_userid')
        batch_op.drop_index('otp_otp')
        batch_op.drop_index('otp_is_encrypted')
        batch_op.drop_index('otp_id')
        batch_op.drop_index('otp_created_at')
        batch_op.alter_column('otp',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('logged_in_users', schema=None) as batch_op:
        batch_op.drop_index('logged_in_user_userid')
        batch_op.drop_index('logged_in_user_srno')
        batch_op.drop_index('logged_in_user_logout_at')
        batch_op.drop_index('logged_in_user_loggedin_at')
        batch_op.drop_index('logged_in_user_is_logout')
        batch_op.drop_index('logged_in_user_is_encrypted')
        batch_op.drop_index('logged_in_user_customer_id')

    with op.batch_alter_table('holiday_master', schema=None) as batch_op:
        batch_op.drop_index('holiday_master_is_encrypted')
        batch_op.drop_index('holiday_master_id')
        batch_op.drop_index('holiday_master_description')
        batch_op.drop_index('holiday_master_day')
        batch_op.drop_index('holiday_master_customer_id')

    with op.batch_alter_table('function_master', schema=None) as batch_op:
        batch_op.drop_index('function_master_is_encrypted')
        batch_op.drop_index('function_master_id')
        batch_op.drop_index('function_master_function_name')
        batch_op.drop_index('function_master_function_code')
        batch_op.drop_index('function_master_created_at')

    with op.batch_alter_table('customer_master', schema=None) as batch_op:
        batch_op.drop_index('customer_master_updated_at')
        batch_op.drop_index('customer_master_is_encrypted')
        batch_op.drop_index('customer_master_customer_name')
        batch_op.drop_index('customer_master_customer_id')
        batch_op.drop_index('customer_master_customer_email')
        batch_op.drop_index('customer_master_created_at')
        batch_op.drop_index('customer_master_active_flag')

    with op.batch_alter_table('business_hour', schema=None) as batch_op:
        batch_op.drop_index('business_hour_weekly_holiday')
        batch_op.drop_index('business_hour_starting_time')
        batch_op.drop_index('business_hour_is_encrypted')
        batch_op.drop_index('business_hour_id')
        batch_op.drop_index('business_hour_ending_time')
        batch_op.drop_index('business_hour_day')
        batch_op.drop_index('business_hour_customer_id')

    with op.batch_alter_table('SLA_master', schema=None) as batch_op:
        batch_op.drop_index('sla_master_ticket_type')
        batch_op.drop_index('sla_master_sub_customer_id')
        batch_op.drop_index('sla_master_severity')
        batch_op.drop_index('sla_master_response_time_sla')
        batch_op.drop_index('sla_master_resolve_time_sla')
        batch_op.drop_index('sla_master_priority')
        batch_op.drop_index('sla_master_is_encrypted')
        batch_op.drop_index('sla_master_id')
        batch_op.drop_index('sla_master_holiday_hour_bypass')
        batch_op.drop_index('sla_master_customer_id')
        batch_op.drop_index('sla_master_created_at')
        batch_op.drop_index('sla_master_business_hr_bypass')

    op.drop_table('SLA_master')
    with op.batch_alter_table('SLA_log', schema=None) as batch_op:
        batch_op.drop_index('sla_log_ticket_status')
        batch_op.drop_index('sla_log_ticket_id')
        batch_op.drop_index('sla_log_sub_customer_id')
        batch_op.drop_index('sla_log_sla_type')
        batch_op.drop_index('sla_log_sla_status')
        batch_op.drop_index('sla_log_sla_start')
        batch_op.drop_index('sla_log_sla_due')
        batch_op.drop_index('sla_log_is_encrypted')
        batch_op.drop_index('sla_log_id')
        batch_op.drop_index('sla_log_customer_id')
        batch_op.drop_index('sla_log_created_at')

    op.drop_table('SLA_log')
    # ### end Alembic commands ###
